### ISSUE TITLE
Provide additional ability to create ObjectProperty 

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-config#110]
Add ability to create object property by parser.  (For now you can create only haveing `preifx` or `bindingMap`)

It has to like this: 
```java
ObjectProperty<T> objectPoerpty(BiFunction<String, Class<? extends T>, T> propertyParse)
```

As a consequence  get rid of  `jsonObjectProperty()`  fgunction

**Comment by aharonha** [comment]
Fixed on #111
