### ISSUE TITLE
ConfigRegistry  <T> T objectValue(String var1, Class<T> var2, T var3) - null for Strings

### ISSUE THREAD

**Issue by guymoragx** [scalecube/scalecube-config#118]
If I want to use ConfigRegistry and pass a String object to 'objectValue' it doesn't return.

That's because in ObjectConfigPropertlyImpl in  
private List<ObjectPropertyField> toPropertyFields(Map<String, String> bindingMap, Class<T> cfgClass)

we have this line:
 if (!Modifier.isStatic(modifiers) && !Modifier.isFinal(modifiers)) {

This filters out strings because their .value field is final.

Fully aware of .stringValue as an alternative but it feels like there's room to allow objectValue to return all the primitive wrapper classes too.

**Comment by guymoragx** [comment]
Yes so this is my code:

public static <T> T ValueOf(String name, T defaultValue, Class<T> valueClass){
        T nonVaultValue = getInstance().objectValue(name, valueClass, defaultValue);
        nonVaultValue = getValueFromVault(name, defaultValue, nonVaultValue, valueClass);

        return nonVaultValue;
    }

You can ignore the second row, 
if I call this method on ("someConfig", "defaultValue", String.class) and someConfig exists so that calling getInstance().stringValue("someConfig", "defaultValue") returns someConfig, I will always get defaultValue becuase String.value gets filtered out and it appears null.

**Comment by aharonha** [comment]
I suppose you want a simple `stringValue`. try it.
If you need some complex type of configuration please do this:
1. create your configuration class with many fields as you want (all primitive types are allowed!)
 (hereby called `com.guymoragx.MyCfg`)
2. put some configuration into Vault:
2.1 `com.guymoragx.MyCfg.stringField1` --> `ca`
2.2 `com.guymoragx.MyCfg.stringField2` --> `fe`
2.3 `com.guymoragx.MyCfg.intField` --> `42`
3. get your configuration:
``` java
MyCfg defaultSettings = new MyCfg("a","b",1); //.....
MyCfg cfg = getInstance().objectValue("com.guymoragx", MyCfg.class, defaultSettings);
 ```

Hope it helps

**Comment by aharonha** [comment]
see also https://github.com/scalecube/scalecube-config/blob/cf06ad9a36b7f38cef0e76f2da588023e28c2aaa/config-examples/src/main/java/io/scalecube/config/examples/JsonObjectExample.java#L23

**Comment by guymoragx** [comment]
I know of stringValue and of objectValue, they are both working great.
However what I wish I had was a method that is capable of parsing both types.
An 'objectValue' that is willing to accept String and friends, because in my code I have a method that manipulates the results of objectValue before returning the configuration.
So the fact that objectValue can't accpet String.class for example, is forcing me to either make multiple helper methods (one that builds on objectValue, one on string, one on double, one on long etc etc) or make one big method with a switch on class type to call the proper method.

So it would really help if objectValue could get the rest of the types it currently can't.

**Comment by ronenhamias** [comment]
can you offer a pull request with these changes? (maybe it will be more clear)
