### ISSUE TITLE
Vault config reload question

### ISSUE THREAD

**Issue by guymoragx** [scalecube/scalecube-config#119]
Hi,
In my code I am using VaultConfigSource to load some configurations from Vault.
I am using a token I generate from kubernetes to access it, that token has a 1 hour timeout.
Afterwards of course whenever vault config tries to reload, it gets a forbidden error.

Is there a way to tell VaultConfigSource to go get a new token (using a method I created) every x amount of time? (or whenever access is forbidden the first time?)

Also is there a way to tell VaultConfigSource to make a callback to a certain method every time configurations are reloaded? 

Thanks.

**Comment by guymoragx** [comment]
A follow up, is it possible to simply disable reloading for specific configuration sources?

**Comment by aharonha** [comment]
I talked with Lior and he told me that the real issue is that the token is not renewed. So in #120  we will renew the token periodically, thus avoiding the need for callback for configuration-reload or to supply a new token whenever it's expired.
Is it good for now?

**Comment by guymoragx** [comment]
Ye that will be good enough for our needs.

**Comment by aharonha** [comment]
Merged and released
